CREATE TABLE Cliente (
	Id SERIAL,
	Nome VARCHAR(100) NOT NULL,
	Documento VARCHAR(30),
	Saldo DOUBLE PRECISION NOT NULL,
	Ativo VARCHAR(30) NOT NULL,
	CONSTRAINT PK_CLiente PRIMARY KEY(Id)
);

CREATE TABLE Pedido(
	Id SERIAL,
	Data Date NOT NULL,
	Valor DOUBLE PRECISION NOT NULL,
	idCliente INTEGER,
	CONSTRAINT PK_Pedido PRIMARY KEY(Id),
	CONSTRAINT FK_Pedido_Cliente FOREIGN KEY(idCliente) REFERENCES Cliente(Id)
);
